import Head from "next/head";
import { CardFilme } from "@/components/cardFilme";
import style from "@/styles/home.module.css";
import axios from "axios";
export default function Home() {
  const url =
    "https://api.themoviedb.org/3/person/popular?language=en-US&page=1";

  const getPopularMovies = () => {
    axios.get(url);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main`}>
        <h1 className="mt-4 text-center"> Populares 2023 </h1>
        <div className={style.cardContainer}>
          <CardFilme />
          <CardFilme />
          <CardFilme />
          <CardFilme />
          <CardFilme />
          <CardFilme />
          <CardFilme />
          <CardFilme />
        </div>
      </main>
    </>
  );
}

//Query //https://api.themoviedb.org/3/search/movie?query=naruto&include_adult=false&language=en-US&page=1
//Popular // https://api.themoviedb.org/3/person/popular?language=en-US&page=1
