import Head from "next/head";
import { CardVideos } from "@/components/cardVideos";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main`}>
        <h1>Start app</h1>
        <CardVideos />
      </main>
    </>
  );
}
