import Head from "next/head";
import { CardFilm } from "@/components/cardFilm";
import style from "@/styles/home.module.css";
import axios from "axios";

export const getServerSideProps = async () => {
  const url =
    "https://api.themoviedb.org/3/person/popular?language=en-US&page=1";

  const config = {
    headers: {
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMzRlYWNiYmM1YmY3YzkzYmI5MDZkMTlkZWY2NWI1YiIsInN1YiI6IjY0YWNhN2I1M2UyZWM4MDBjYmNmMjczZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.maMoeOYRoxeMx3POTZo1zRDvS2KEFpb0a7rlK5EvaUM",
    },
  };

  try {
    const response = await axios.get(url, config);
    const popularMovies = response.data.results;

    return { props: { popularMovies } };
  } catch (error) {
    console.log("My erro is", error);

    return {
      props: {
        popularMovies:
          "Ocorreu um erro interno no servidor, por favor tente novamente mais tarde",
      },
    };
  }
};

export default function Home({ popularMovies }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`main`}>
        <h1 className="mt-4 text-center"> Populares 2023 </h1>
        <div className={style.cardContainer}>
          {popularMovies.map((film) => {
            const movie = film.known_for[0];
            const baseUrl = "https://image.tmdb.org/t/p/w500";
            const fullUrl = baseUrl + movie.backdrop_path;

            return (
              <div key={film.id}>
                <CardFilm
                  filmImg={fullUrl}
                  filmName={movie.name || movie.title}
                  filmDate={movie.first_air_date || movie.release_date}
                  filmRate={movie.vote_average}
                />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

//Query //https://api.themoviedb.org/3/search/movie?query=naruto&include_adult=false&language=en-US&page=1
//Popular // https://api.themoviedb.org/3/person/popular?language=en-US&page=1
